# SPDX-License-Identifier: GPL-2.0
#
# Makefile for PCI Endpoint Functions
#

obj-$(CONFIG_PCI_EPF_TEST)		+= pci-epf-test.o
obj-$(CONFIG_PCI_EPF_AMBA_TEST)		+= pci-epf-amba-test.o
obj-$(CONFIG_PCI_EPF_NTB)		+= pci-epf-ntb.o
obj-$(CONFIG_AMBARELLA_EXCALIBUR_EP)		+= ambarella_excalibur_ep.o
obj-$(CONFIG_AMBARELLA_MOEMOEKYUN_EP)		+= ambarella_moemoekyun_ep.o
obj-$(CONFIG_AMBARELLA_RAINY_EP)		+= ambarella_rainy_ep.o
obj-$(CONFIG_AMBARELLA_BSB_EP)		+= ambarella_bsb_ep.o
