# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2004-2011, Ambarella, Inc.
#

obj-$(CONFIG_ARCH_AMBARELLA) += soc.o iav_helper.o syncproc.o io.o epf-core.o pci-util.o
obj-$(CONFIG_AMBARELLA_SUPPORT_GDMA) += gdma.o
obj-$(CONFIG_AMBARELLA_LPDDR5_ADJUST) += lpddr5_adjust.o
obj-$(CONFIG_AMBARELLA_EXCALIBUR_RC)	        += ambarella_excalibur_rc.o
obj-$(CONFIG_AMBARELLA_MOEMOEKYUN_RC)	        += ambarella_moemoekyun_rc.o
obj-$(CONFIG_AMBARELLA_NEKO_EP)	        += neko_ep.o
obj-$(CONFIG_AMBARELLA_RAINY_RC)	        += ambarella_rainy_rc.o
obj-$(CONFIG_AMBARELLA_BSB_RC)	        += ambarella_bsb_rc.o
