ccflags-y := -DDEBUG
obj-$(CONFIG_SAMPLE_AMBARELLA_MOEMOEKYUN_EP) += moemoekyun_EP_ep_ob.o
obj-$(CONFIG_SAMPLE_AMBARELLA_MOEMOEKYUN_EP) += moemoekyun_EP_ep_ib.o
obj-$(CONFIG_SAMPLE_AMBARELLA_MOEMOEKYUN_EP) += moemoekyun_EP_rc_ib.o
obj-$(CONFIG_SAMPLE_AMBARELLA_MOEMOEKYUN_EP) += moemoekyun_EP_rc_ob.o
#
obj-$(CONFIG_SAMPLE_AMBARELLA_MOEMOEKYUN_RC) += moemoekyun_RC_rc_ib.o
obj-$(CONFIG_SAMPLE_AMBARELLA_MOEMOEKYUN_RC) += moemoekyun_RC_rc_ob.o
obj-$(CONFIG_SAMPLE_AMBARELLA_MOEMOEKYUN_RC) += moemoekyun_RC_ep_ob.o
obj-$(CONFIG_SAMPLE_AMBARELLA_MOEMOEKYUN_RC) += moemoekyun_RC_ep_ib.o
